#!/usr/bin/env python3

"""
SAM-Enhanced Battery Material Segmentation with Gaussian Mixture Models

This module combines Segment Anything Model (SAM) masks with Gaussian Mixture Model (GMM)
statistical classification to accurately segment battery materials in SEM images.

Key Features:
    - Identifies 4 material types: Voids, Carbon Black, LFP, NaCl
    - Uses SAM masks for precise particle boundary identification
    - Employs Gaussian Mixture Models for statistical classification
    - Includes autoencoder-based feature extraction for improved accuracy
    - Automatically removes microscope metadata bars
    - Provides visualization and statistics of material distribution
    - Exports results to CSV format for further analysis
"""

import os
import sys
import pickle
import argparse
import numpy as np
import cv2
import matplotlib.pyplot as plt
from PIL.Image import alpha_composite
from matplotlib.colors import ListedColormap
import pandas as pd
from scipy import ndimage
from skimage import filters, measure, morphology
from sklearn.mixture import GaussianMixture
from sklearn.preprocessing import StandardScaler
import tensorflow as tf
from tensorflow.keras import layers, models


def load_sem_image(image_path):
    """Load a SEM image from disk.

    Args:
        image_path (str): Path to the SEM image file.

    Returns:
        numpy.ndarray: Grayscale image as a 2D numpy array.

    Raises:
        FileNotFoundError: If the specified image file doesn't exist.
    """
    img = cv2.imread(image_path, cv2.IMREAD_GRAYSCALE)
    if img is None:
        raise FileNotFoundError(f"Image not found at {image_path}")
    return img


def detect_metadata_bar(img, threshold_percent=0.1):
    """Detect and create a mask for the microscope metadata bar.

    Uses edge detection to identify text and information bars commonly
    present in SEM images.

    Args:
        img (numpy.ndarray): Original grayscale image.
        threshold_percent (float): Percentage of image height to check for
                                  abrupt changes indicating metadata.

    Returns:
        numpy.ndarray: Binary mask where True indicates pixels to keep (not metadata).
    """
    h, w = img.shape

    # Start by assuming the metadata bar is at the bottom of the image
    metadata_mask = np.ones_like(img, dtype=bool)

    # Check for horizontal lines that might indicate metadata bar
    # Use horizontal gradient to detect abrupt changes
    sobelx = cv2.Sobel(img, cv2.CV_64F, 1, 0, ksize=3)
    sobely = cv2.Sobel(img, cv2.CV_64F, 0, 1, ksize=3)

    # Look at the bottom part of the image
    bottom_region_height = int(h * threshold_percent)
    bottom_region = img[-bottom_region_height:]

    # Check for text-like features in the bottom region
    horizontal_sum = np.sum(np.abs(sobelx[-bottom_region_height:]), axis=1)
    vertical_sum = np.sum(np.abs(sobely[-bottom_region_height:]), axis=1)

    # Normalize the sums
    horizontal_sum = horizontal_sum / w
    vertical_sum = vertical_sum / w

    # Find rows with high horizontal and vertical gradients (typical for text)
    text_threshold = np.max(horizontal_sum) * 0.3
    potential_text_rows = np.where(horizontal_sum > text_threshold)[0]

    # If we found potential text rows, set the mask accordingly
    if len(potential_text_rows) > 0:
        # Find the first row with significant text features from the bottom
        first_text_row = potential_text_rows[0]
        metadata_height = min(80, bottom_region_height)  # At least 80 pixels or what we checked

        # Set the bottom part as metadata (mask = False)
        metadata_mask[-metadata_height:, :] = False

        print(f"Detected metadata bar of height {metadata_height} pixels")
    else:
        # Fallback: use a fixed height for metadata bar
        metadata_mask[-80:, :] = False
        print(f"Using default metadata height of 80 pixels")

    return metadata_mask


def preprocess_image(img):
    """Apply preprocessing to enhance image features.

    Applies a sequence of image processing techniques to enhance contrast
    and reduce noise in the SEM image.

    Args:
        img (numpy.ndarray): Original grayscale image.

    Returns:
        numpy.ndarray: Enhanced grayscale image with improved contrast and reduced noise.
    """
    # Apply median filter to reduce noise
    img_median = cv2.medianBlur(img, 3)

    # Apply CLAHE for better contrast
    clahe = cv2.createCLAHE(clipLimit=2.0, tileGridSize=(8, 8))
    img_clahe = clahe.apply(img_median)

    # Apply slight Gaussian blur
    img_enhanced = cv2.GaussianBlur(img_clahe, (3, 3), 0)

    return img_enhanced


def load_sam_masks(pickle_path):
    """Load segmentation masks from SAM pickle file.

    Loads and extracts masks generated by the Segment Anything Model (SAM),
    which identify individual particles in the SEM image.

    Args:
        pickle_path (str): Path to the pickle file containing SAM masks.

    Returns:
        list: List of binary masks (numpy.ndarray) for each detected particle,
              or None if loading fails.
    """
    try:
        with open(pickle_path, 'rb') as f:
            data = pickle.load(f)

        # Extract segmentation masks
        masks = []
        for item in data:
            if isinstance(item, dict) and 'segmentation' in item:
                masks.append(item['segmentation'])

        print(f"Loaded {len(masks)} masks from SAM")
        return masks

    except Exception as e:
        print(f"Error loading pickle file: {e}")
        return None


def build_autoencoder(input_shape=(32, 32, 1)):
    """Build a convolutional autoencoder for feature extraction.

    Creates a deep neural network with an encoder-decoder architecture
    for learning compact representations of particle images.

    Args:
        input_shape (tuple): Shape of input image patches (height, width, channels).

    Returns:
        tuple: (autoencoder, encoder) - complete model and feature extractor component.
    """
    # Encoder
    inputs = layers.Input(shape=input_shape)

    # First block
    x = layers.Conv2D(16, (3, 3), activation='relu', padding='same')(inputs)
    x = layers.BatchNormalization()(x)
    x = layers.MaxPooling2D((2, 2), padding='same')(x)

    # Second block
    x = layers.Conv2D(32, (3, 3), activation='relu', padding='same')(x)
    x = layers.BatchNormalization()(x)
    x = layers.MaxPooling2D((2, 2), padding='same')(x)

    # Third block
    x = layers.Conv2D(64, (3, 3), activation='relu', padding='same')(x)
    x = layers.BatchNormalization()(x)
    x = layers.MaxPooling2D((2, 2), padding='same')(x)

    # Latent representation
    x = layers.Flatten()(x)
    latent = layers.Dense(64, activation='relu')(x)

    # Decoder
    x = layers.Dense(4 * 4 * 64, activation='relu')(latent)
    x = layers.Reshape((4, 4, 64))(x)

    x = layers.Conv2DTranspose(64, (3, 3), strides=2, activation='relu', padding='same')(x)
    x = layers.BatchNormalization()(x)

    x = layers.Conv2DTranspose(32, (3, 3), strides=2, activation='relu', padding='same')(x)
    x = layers.BatchNormalization()(x)

    x = layers.Conv2DTranspose(16, (3, 3), strides=2, activation='relu', padding='same')(x)
    x = layers.BatchNormalization()(x)

    outputs = layers.Conv2D(1, (3, 3), activation='sigmoid', padding='same')(x)

    # Define models
    autoencoder = models.Model(inputs, outputs)
    encoder = models.Model(inputs, latent)

    # Compile autoencoder
    autoencoder.compile(optimizer='adam', loss='mse')

    return autoencoder, encoder


def extract_standardized_particle_patches(img, masks, metadata_mask=None, target_size=32):
    """Extract standardized image patches with aspect ratio preservation.

    Implements the whiteboard steps exactly:
    1. Get BBox coordinates from masks
    2. Apply BBox coordinates to original image
    3. Fill "False" areas with 0 (black)
    4. Pad borders to create squares
    5. Find highest value of all dimensions
    6. Pad each square to the maximum dimension
    7. Resize each square to target size

    Args:
        img (numpy.ndarray): Original or preprocessed SEM image.
        masks (list): List of binary masks identifying particles.
        metadata_mask (numpy.ndarray, optional): Binary mask for valid image areas.
        target_size (int): Final size of extracted square patches in pixels.

    Returns:
        numpy.ndarray: Array of standardized image patches.
    """
    patches = []
    raw_patches = []

    # First pass: Extract each particle and find maximum dimension
    max_dim = 0

    for mask in masks:
        # Skip masks with no pixels or that overlap with metadata
        if np.sum(mask) == 0:
            continue

        if metadata_mask is not None:
            # Skip if mask significantly overlaps with metadata region
            if np.sum(mask & (~metadata_mask)) > 0.2 * np.sum(mask):
                continue

        # Step 1: Get particle bounding box
        y_indices, x_indices = np.where(mask)
        if len(y_indices) == 0:
            continue

        y_min, y_max = np.min(y_indices), np.max(y_indices)
        x_min, x_max = np.min(x_indices), np.max(x_indices)

        # Step 2: Extract the patch (crop using bounding box)
        patch = img[y_min:y_max + 1, x_min:x_max + 1].copy()

        # Create mask for this specific patch
        local_mask = mask[y_min:y_max + 1, x_min:x_max + 1]

        # Step 3: Fill "False" areas with 0 (background)
        patch[~local_mask] = 0

        # Record dimensions for later use
        h, w = patch.shape
        max_dim = max(max_dim, h, w)

        raw_patches.append(patch)

    if len(raw_patches) == 0:
        return np.array([])

    # Second pass: Process all patches to same dimensions
    for patch in raw_patches:
        h, w = patch.shape

        # Step 4: Pad to make square
        max_side = max(h, w)
        square_patch = np.zeros((max_side, max_side), dtype=patch.dtype)
        y_offset = (max_side - h) // 2
        x_offset = (max_side - w) // 2
        square_patch[y_offset:y_offset + h, x_offset:x_offset + w] = patch

        # Step 5-6: Pad to match largest dimension across all particles
        if max_side < max_dim:
            padded_patch = np.zeros((max_dim, max_dim), dtype=patch.dtype)
            offset = (max_dim - max_side) // 2
            padded_patch[offset:offset + max_side, offset:offset + max_side] = square_patch
            standardized = padded_patch
        else:
            standardized = square_patch

        # Step 7: Resize to target size
        resized = cv2.resize(standardized, (target_size, target_size),
                             interpolation=cv2.INTER_AREA)

        patches.append(resized)

    return np.array(patches)


def extract_mask_features(img, enhanced_img, mask, metadata_mask):
    """Extract features from a specific mask region.

    Calculates intensity, texture, and shape features from the region of the
    image defined by the mask.

    Args:
        img (numpy.ndarray): Original grayscale image.
        enhanced_img (numpy.ndarray): Preprocessed image with enhanced features.
        mask (numpy.ndarray): Binary mask defining the region of interest.
        metadata_mask (numpy.ndarray): Binary mask defining valid image areas.

    Returns:
        dict: Dictionary of features including intensity statistics, texture metrics,
              and shape characteristics, or None if the mask has too few pixels.
    """
    # Apply the metadata mask to the particle mask
    valid_mask = mask & metadata_mask

    # Skip empty masks or masks with too few pixels
    if np.sum(valid_mask) < 50:
        return None

    # Get bounding box coordinates
    y_indices, x_indices = np.where(valid_mask)
    y_min, y_max = np.min(y_indices), np.max(y_indices)
    x_min, x_max = np.min(x_indices), np.max(x_indices)
    height = y_max - y_min + 1
    width = x_max - x_min + 1

    # Extract region of interest from original and enhanced images
    masked_img = img[valid_mask]
    masked_enhanced = enhanced_img[valid_mask]

    # Calculate intensity features
    mean_intensity = np.mean(masked_img)
    std_intensity = np.std(masked_img)
    median_intensity = np.median(masked_img)
    min_intensity = np.min(masked_img)
    max_intensity = np.max(masked_img)

    # Enhanced image features
    enhanced_mean = np.mean(masked_enhanced)
    enhanced_std = np.std(masked_enhanced)

    # Calculate texture features using GLCM
    texture_complexity = std_intensity / (mean_intensity + 1e-10)

    # Calculate shape features
    area = np.sum(valid_mask)

    # Create contour for perimeter calculation
    contour = valid_mask.astype(np.uint8) * 255
    contours, _ = cv2.findContours(contour, cv2.RETR_EXTERNAL, cv2.CHAIN_APPROX_SIMPLE)
    if len(contours) > 0:
        perimeter = cv2.arcLength(contours[0], True)
    else:
        perimeter = 0

    # Calculate compactness (circularity)
    compactness = 4 * np.pi * area / (perimeter * perimeter + 1e-10) if perimeter > 0 else 0

    # Additional shape metrics
    equivalent_diameter = np.sqrt(4 * area / np.pi)
    extent = area / (height * width) if (height * width) > 0 else 0

    # Solidity calculation (area / convex hull area)
    if len(contours) > 0:
        hull = cv2.convexHull(contours[0])
        hull_area = cv2.contourArea(hull)
        solidity = area / hull_area if hull_area > 0 else 0
    else:
        solidity = 0

    # Return feature dictionary
    features = {
        'mean_intensity': mean_intensity,
        'std_intensity': std_intensity,
        'median_intensity': median_intensity,
        'min_intensity': min_intensity,
        'max_intensity': max_intensity,
        'enhanced_mean': enhanced_mean,
        'enhanced_std': enhanced_std,
        'texture_complexity': texture_complexity,
        'area': area,
        'perimeter': perimeter,
        'compactness': compactness,
        'equivalent_diameter': equivalent_diameter,
        'extent': extent,
        'solidity': solidity,
        'aspect_ratio': width / height if height > 0 else 1
    }

    return features


def train_autoencoder(img, enhanced_img, masks, metadata_mask, epochs=50):
    """Train autoencoder on particle patches for feature extraction.

    Extracts patches from the image, then trains an autoencoder to learn
    a compact representation of particle features.

    Args:
        img (numpy.ndarray): Original grayscale image.
        enhanced_img (numpy.ndarray): Preprocessed image with enhanced features.
        masks (list): List of binary masks identifying particles.
        metadata_mask (numpy.ndarray): Binary mask defining valid image areas.
        epochs (int): Number of training epochs.

    Returns:
        tensorflow.keras.Model: Trained encoder model for feature extraction,
                               or None if training fails.
    """
    # Extract patches for training using the standardized method
    print("Extracting patches for autoencoder training...")
    patches = extract_standardized_particle_patches(enhanced_img, masks, metadata_mask, target_size=32)

    if len(patches) < 10:
        print("Warning: Not enough particles detected for autoencoder training")
        return None

    # Normalize patches
    patches_norm = patches.astype('float32') / 255.0
    patches_norm = patches_norm.reshape(-1, 32, 32, 1)

    # Build and train the autoencoder
    print(f"Training autoencoder on {len(patches_norm)} patches for {epochs} epochs")
    autoencoder, encoder = build_autoencoder(input_shape=(32, 32, 1))

    # Train the autoencoder
    autoencoder.fit(
        patches_norm, patches_norm,
        epochs=epochs,
        batch_size=16,
        shuffle=True,
        validation_split=0.2,
        verbose=1
    )

    return encoder


def extract_autoencoder_features(img, mask, encoder, metadata_mask):
    """Extract autoencoder features for a mask.

    Uses a trained encoder to extract latent representation features
    from the image region defined by the mask, using the standardized
    aspect ratio preservation approach.

    Args:
        img (numpy.ndarray): Image to extract features from.
        mask (numpy.ndarray): Binary mask defining the region of interest.
        encoder (tensorflow.keras.Model): Trained encoder model.
        metadata_mask (numpy.ndarray): Binary mask defining valid image areas.

    Returns:
        numpy.ndarray: Feature vector from encoder's latent space,
                      or None if the mask is too small.
    """
    # Apply metadata mask
    valid_mask = mask & metadata_mask

    # Skip if mask is too small
    if np.sum(valid_mask) < 50:
        return None

    # Get particle bounding box
    y_indices, x_indices = np.where(valid_mask)
    y_min, y_max = np.min(y_indices), np.max(y_indices)
    x_min, x_max = np.min(x_indices), np.max(x_indices)

    # Extract the patch (crop using bounding box)
    patch = img[y_min:y_max + 1, x_min:x_max + 1].copy()

    # Create mask for this specific patch
    local_mask = mask[y_min:y_max + 1, x_min:x_max + 1]

    # Fill non-mask areas with black
    patch[~local_mask] = 0

    # Make it square by padding
    h, w = patch.shape
    max_side = max(h, w)
    square_patch = np.zeros((max_side, max_side), dtype=patch.dtype)
    y_offset = (max_side - h) // 2
    x_offset = (max_side - w) // 2
    square_patch[y_offset:y_offset + h, x_offset:x_offset + w] = patch

    # Resize to encoder input size
    resized = cv2.resize(square_patch, (32, 32), interpolation=cv2.INTER_AREA)

    # Normalize and reshape for encoder
    patch_norm = resized.astype('float32') / 255.0
    patch_norm = patch_norm.reshape(1, 32, 32, 1)

    # Get feature vector
    features = encoder.predict(patch_norm, verbose=0)[0]

    return features


def train_gmm(mask_features, n_components=4, covariance_type='full'):
    """Train a Gaussian Mixture Model on mask features.

    Fits a GMM to the extracted particle features to enable material classification.

    Args:
        mask_features (list): List of feature dictionaries for each particle.
        n_components (int): Number of Gaussian components (material types) to model.
        covariance_type (str): Type of covariance parameter for GMM.

    Returns:
        tuple: (gmm, scaler, cluster_to_material) where:
            - gmm is the trained GaussianMixture model
            - scaler is the StandardScaler used for feature normalization
            - cluster_to_material is a dictionary mapping cluster indices to material classes
            or None if training fails.
    """
    # Extract the relevant features for GMM training
    feature_matrix = []

    # For each mask with features
    for features in mask_features:
        if features is not None:
            # Create feature vector (focusing on intensity-related features)
            feature_vector = [
                features['mean_intensity'],
                features['enhanced_mean'],
                features['std_intensity'],
                features['texture_complexity']
            ]
            feature_matrix.append(feature_vector)

    # Convert to numpy array
    feature_matrix = np.array(feature_matrix)

    # Check if we have enough data
    if len(feature_matrix) < n_components:
        print(f"Warning: Only {len(feature_matrix)} valid particles for GMM training, needed {n_components}")
        if len(feature_matrix) == 0:
            return None
        n_components = min(len(feature_matrix), 3)  # Reduced number of components

    # Normalize features
    scaler = StandardScaler()
    feature_matrix_scaled = scaler.fit_transform(feature_matrix)

    # Train GMM
    gmm = GaussianMixture(
        n_components=n_components,
        covariance_type=covariance_type,
        random_state=42,
        max_iter=200
    )
    gmm.fit(feature_matrix_scaled)

    # Order the components by the mean intensity of their center
    # This helps align GMM clusters with the expected materials
    centers = gmm.means_

    # Transform the centers back to original scale for intensity comparison
    centers_original = scaler.inverse_transform(centers)

    # Sort by the first feature (mean_intensity)
    sorted_idx = np.argsort(centers_original[:, 0])

    # Map cluster indices to material classes based on intensity
    # 0: void (not used here since voids are defined by thresholding)
    # 1: LFP (darkest) - SWAPPED from previous code
    # 2: Carbon Black (medium) - SWAPPED from previous code
    # 3: NaCl (brightest)
    cluster_to_material = {}

    if n_components == 3:
        # We have 3 clusters: LFP, Carbon Black, NaCl
        material_map = {0: 1, 1: 2, 2: 3}  # Map to LFP=1, Carbon Black=2, NaCl=3
        for i, idx in enumerate(sorted_idx):
            cluster_to_material[idx] = material_map[i]
    else:
        # Handle case with 4 clusters
        # The darkest cluster might be voids or LFP
        darkest_idx = sorted_idx[0]
        darkest_intensity = centers_original[darkest_idx, 0]

        if darkest_intensity < 40:  # If very dark, it's void
            # Skip the darkest cluster and assign 1, 2, 3 to the rest
            cluster_to_material[darkest_idx] = 0  # void
            material_map = {0: 1, 1: 2, 2: 3}  # Map to LFP=1, Carbon Black=2, NaCl=3
            for i, idx in enumerate(sorted_idx[1:4]):
                cluster_to_material[idx] = material_map[i]
        else:
            # All clusters are materials
            material_map = {0: 1, 1: 2, 2: 3}  # Map to LFP=1, Carbon Black=2, NaCl=3
            for i, idx in enumerate(sorted_idx[:3]):  # Only use first 3 clusters
                cluster_to_material[idx] = material_map[i]

    # Store the scaler with the GMM for later use
    return gmm, scaler, cluster_to_material


def classify_with_gmm(particle_features, gmm, scaler, cluster_to_material):
    """Classify particles using the trained GMM.

    Predicts material class for a particle based on its features using
    the trained Gaussian Mixture Model.

    Args:
        particle_features (dict): Dictionary of features for a particle.
        gmm (GaussianMixture): Trained GMM model.
        scaler (StandardScaler): Feature scaler used during GMM training.
        cluster_to_material (dict): Mapping from cluster indices to material classes.

    Returns:
        tuple: (material_class, confidence) where:
            - material_class is an integer identifying the material (1-3)
            - confidence is a float indicating classification confidence
            or None if classification fails.
    """
    if particle_features is None:
        return None

    # Create feature vector for GMM classification
    feature_vector = [
        particle_features['mean_intensity'],
        particle_features['enhanced_mean'],
        particle_features['std_intensity'],
        particle_features['texture_complexity']
    ]

    # Reshape and scale
    feature_vector = np.array(feature_vector).reshape(1, -1)
    feature_vector_scaled = scaler.transform(feature_vector)

    # Get GMM probability and prediction
    prob = gmm.predict_proba(feature_vector_scaled)[0]
    cluster = np.argmax(prob)

    # Convert to material class
    if cluster in cluster_to_material:
        material = cluster_to_material[cluster]
        confidence = prob[cluster]
        return material, confidence
    else:
        # Fallback: classify based on intensity only
        mean_intensity = particle_features['mean_intensity']

        if mean_intensity < 60:
            return 1, 0.8  # LFP (darkest)
        elif mean_intensity < 150:
            return 2, 0.8  # Carbon Black (medium)
        else:
            return 3, 0.8  # NaCl (brightest)


def segment_with_gmm_sam(image_path, masks_path=None, output_dir=None,
                         void_threshold=10, epochs=50, gmm_components=4):
    """Perform segmentation using SAM masks, autoencoder, and Gaussian Mixture Model.

    Main function that orchestrates the complete segmentation pipeline:
    1. Loads image and SAM masks
    2. Detects and masks metadata regions
    3. Enhances image with preprocessing
    4. Trains autoencoder for feature extraction
    5. Extracts features from particle masks
    6. Trains GMM for material classification
    7. Classifies each particle using GMM
    8. Creates and post-processes segmentation map
    9. Calculates material statistics
    10. Visualizes and exports results

    Args:
        image_path (str): Path to the SEM image.
        masks_path (str, optional): Path to the SAM masks pickle file.
                                   If None, inferred from image_path.
        output_dir (str, optional): Directory to save results.
                                   If None, results are not saved.
        void_threshold (int): Intensity threshold to classify pixels as voids.
        epochs (int): Number of epochs for autoencoder training.
                     Set to 0 to skip autoencoder.
        gmm_components (int): Number of components for GMM.

    Returns:
        tuple: (segmentation, stats) where:
            - segmentation is a numpy.ndarray with class labels
            - stats is a dictionary with material statistics
    """
    # If masks_path is not provided, infer it from image_path
    if masks_path is None:
        base_name = os.path.splitext(image_path)[0]
        masks_path = f"{base_name}.pkl"

    print(f"Processing {os.path.basename(image_path)}")
    print(f"Using mask file: {os.path.basename(masks_path)}")
    print(f"Parameters: Void threshold={void_threshold}, GMM components={gmm_components}")

    # Create output directory if needed
    if output_dir is not None and not os.path.exists(output_dir):
        os.makedirs(output_dir)

    # Step 1: Load image and masks
    img = load_sem_image(image_path)

    # Detect and mask the metadata bar
    metadata_mask = detect_metadata_bar(img)

    # Enhance image
    enhanced_img = preprocess_image(img)

    # Load SAM masks
    masks = load_sam_masks(masks_path)

    if not masks:
        print(f"Error: No valid masks found in {masks_path}")
        return None, None

    # Step 2: Prepare data for GMM
    print("Extracting features from particles...")

    # First, create a combined particle mask from all SAM masks
    particle_mask = np.zeros_like(img, dtype=bool)
    for mask in masks:
        particle_mask = particle_mask | mask

    # Apply metadata mask to particle mask
    particle_mask = particle_mask & metadata_mask

    # Step 3: Train autoencoder (optional but recommended)
    use_autoencoder = (epochs > 0)
    encoder = None

    if use_autoencoder:
        encoder = train_autoencoder(img, enhanced_img, masks, metadata_mask, epochs)

    # Step 4: Extract features from each mask
    mask_features = []
    valid_masks = []

    for mask in masks:
        # Extract basic features
        features = extract_mask_features(img, enhanced_img, mask, metadata_mask)

        if features is not None:
            # Add autoencoder features if available
            if encoder is not None:
                ae_features = extract_autoencoder_features(enhanced_img, mask, encoder, metadata_mask)
                if ae_features is not None:
                    features['autoencoder'] = ae_features

            mask_features.append(features)
            valid_masks.append(mask & metadata_mask)

    # Step 5: Train GMM on the features
    print(f"Training GMM with {len(mask_features)} particles and {gmm_components} components...")
    gmm_result = train_gmm(mask_features, n_components=gmm_components)

    if gmm_result is None:
        print("Error: GMM training failed! Falling back to intensity-based classification...")
        # Create a segmentation using traditional thresholding
        segmentation = np.zeros_like(img, dtype=np.uint8)

        # Mark voids
        segmentation[img < void_threshold] = 0

        # Classify particles using intensity thresholds
        for i, (mask, features) in enumerate(zip(valid_masks, mask_features)):
            if features is None:
                continue

            mean_intensity = features['mean_intensity']

            if mean_intensity < 60:
                segmentation[mask] = 1  # LFP (darkest)
            elif mean_intensity < 150:
                segmentation[mask] = 2  # Carbon Black (medium)
            else:
                segmentation[mask] = 3  # NaCl (brightest)
    else:
        # Unpack GMM results
        gmm, scaler, cluster_to_material = gmm_result

        # Step 6: Create initial segmentation using GMM-classified masks
        segmentation = np.zeros_like(img, dtype=np.uint8)

        # First, identify clear voids by thresholding
        void_regions = (img < void_threshold) & metadata_mask & (~particle_mask)
        segmentation[void_regions] = 0

        # Classify each mask using GMM
        gmm_labels = []
        gmm_confidences = []

        for i, (mask, features) in enumerate(zip(valid_masks, mask_features)):
            if features is None:
                gmm_labels.append(None)
                gmm_confidences.append(0)
                continue

            # Classify with GMM
            result = classify_with_gmm(features, gmm, scaler, cluster_to_material)

            if result is None:
                gmm_labels.append(None)
                gmm_confidences.append(0)
                continue

            material, confidence = result
            gmm_labels.append(material)
            gmm_confidences.append(confidence)

            # Apply label to segmentation
            segmentation[mask] = material

        # Step 7: Classify remaining unclassified regions
        unclassified = (segmentation == 0) & (~void_regions) & metadata_mask

        if np.any(unclassified):
            print(f"Classifying {np.sum(unclassified)} unclassified pixels...")

            # Create a distance map to each material
            distance_maps = np.zeros((img.shape[0], img.shape[1], 3))

            for material in range(1, 4):
                material_mask = (segmentation == material)
                if np.any(material_mask):
                    distance_maps[:, :, material - 1] = ndimage.distance_transform_edt(~material_mask)

            # Get typical intensities for each material from GMM means
            if gmm is not None:
                means = scaler.inverse_transform(gmm.means_)
                mean_intensities = []

                for cluster in range(gmm_components):
                    if cluster in cluster_to_material and cluster_to_material[cluster] > 0:
                        material = cluster_to_material[cluster]
                        intensity = means[cluster, 0]  # Mean intensity feature
                        mean_intensities.append((material, intensity))

                # Sort by material class
                mean_intensities.sort()

                # Get locations of unclassified pixels
                unclass_y, unclass_x = np.where(unclassified)

                # For each unclassified pixel
                for i in range(len(unclass_y)):
                    y, x = unclass_y[i], unclass_x[i]
                    intensity = img[y, x]

                    # Get distances to each material
                    distances = distance_maps[y, x]

                    # Weight distances by intensity difference
                    weighted_distances = np.zeros(3)

                    for j, (material, mean_int) in enumerate(mean_intensities):
                        # Calculate distance penalty based on intensity difference
                        int_diff = abs(intensity - mean_int)
                        int_penalty = int_diff / 255.0

                        # Adjust distance by intensity similarity
                        weighted_distances[material - 1] = distances[material - 1] * (1 + int_penalty)

                    # Assign to material with smallest weighted distance
                    material = np.argmin(weighted_distances) + 1
                    segmentation[y, x] = material

    # Step 8: Post-process the segmentation for coherent regions
    print("Post-processing segmentation for coherent regions...")

    # Apply morphological operations to smooth boundaries
    # First clean up each material separately
    processed = segmentation.copy()

    for material in range(1, 4):  # Skip voids
        material_mask = (processed == material)

        # Close small gaps
        closed = morphology.closing(material_mask, morphology.disk(2))

        # Remove small isolated regions (size depends on material)
        min_size = 20 if material != 2 else 50  # Larger for Carbon Black (now class 2)
        cleaned = morphology.remove_small_objects(closed, min_size=min_size)

        # Fill small holes
        filled = ndimage.binary_fill_holes(cleaned)

        # Update segmentation
        processed[material_mask & (~filled)] = 0  # Removed regions become void
        processed[(~material_mask) & filled & metadata_mask] = material  # Added regions

    # Ensure metadata area is blacked out
    processed[~metadata_mask] = 0

    # Step 9: Calculate material statistics
    stats = calculate_material_stats(processed, metadata_mask)

    alpha = 0.6
    # Step 10: Visualize results
    fig = visualize_segmentation(img, processed, image_path, metadata_mask, alpha=alpha)

    # Step 11: Save results if output directory is provided
    if output_dir:
        base_name = os.path.splitext(os.path.basename(image_path))[0]

        # Save visualization
        output_image_path = os.path.join(output_dir, f"{base_name}_gmm_sam_segmentation.png")
        fig.savefig(output_image_path, dpi=300, bbox_inches='tight')
        print(f"Saved segmentation visualization to: {output_image_path}")

        # Export to CSV
        output_csv_path = os.path.join(output_dir, f"{base_name}_gmm_sam_segmentation.csv")
        export_to_csv(processed, image_path, output_csv_path, metadata_mask)
        print(f"Saved segmentation data to: {output_csv_path}")

    plt.close(fig)  # Close the figure to avoid display in notebooks

    return processed, stats


def visualize_segmentation(original_img, segmented, image_path, metadata_mask=None, alpha=0.6):
    """Create visualization of the segmentation results.

    Creates a figure with side-by-side comparison of original image and
    segmentation results with semi-transparent colors.

    Args:
        original_img (numpy.ndarray): Original SEM image.
        segmented (numpy.ndarray): Segmentation map with material classes.
        image_path (str): Path to the original image file (for title).
        metadata_mask (numpy.ndarray, optional): Binary mask defining valid image areas.
        alpha (float, optional): Opacity of segmentation colors (0-1). Defaults to 0.6.

    Returns:
        matplotlib.figure.Figure: Figure object with visualization.
    """
    # Updated material labels with LFP and Carbon Black swapped
    material_labels = ["Voids", "LFP", "Carbon Black", "NaCl"]
    colors = ['black', 'gray', 'green', 'white']

    # Create figure
    fig, (ax1, ax2) = plt.subplots(1, 2, figsize=(14, 7))

    # Create a copy of the original for visualization
    vis_img = original_img.copy()

    # If we have a metadata mask, apply it
    if metadata_mask is not None:
        # Make a black area where metadata is
        vis_img = vis_img.copy()
        vis_img[~metadata_mask] = 0

    # Plot original image
    ax1.imshow(vis_img, cmap='gray')
    ax1.set_title("Original SEM Image", fontsize=14)
    ax1.axis('off')

    # Create visualization copy of segmentation
    vis_seg = segmented.copy()

    # If we have a metadata mask, set metadata area to class 0 (voids/black)
    if metadata_mask is not None:
        vis_seg[~metadata_mask] = 0

    # First display the grayscale image as background
    ax2.imshow(vis_img, cmap='gray')

    # Create colored overlay with transparency
    overlay = np.zeros((*vis_img.shape, 4))  # RGBA

    # Set colors with transparency for each class
    for i in range(4):
        if i == 0:  # Voids are fully transparent
            continue

        mask = (vis_seg == i)
        if np.any(mask):
            # Convert color string to RGBA
            color = plt.cm.colors.to_rgba(colors[i])
            # Set this class's pixels to its color with transparency
            overlay[mask] = (*color[:3], alpha)

    # Display the overlay on top of grayscale image
    ax2.imshow(overlay)
    ax2.set_title("GMM+SAM Segmentation", fontsize=14)
    ax2.axis('off')

    # Add filename as figure title
    plt.suptitle(f"Battery Material Analysis: {os.path.basename(image_path)}", fontsize=16)

    # Create legend
    legend_handles = [plt.Rectangle((0, 0), 1, 1, color=colors[i]) for i in range(len(material_labels))]
    fig.legend(legend_handles,
               [f"{i}: {material_labels[i]}" for i in range(len(material_labels))],
               loc="lower center", ncol=len(material_labels), frameon=False, fontsize=12)

    plt.tight_layout()
    plt.subplots_adjust(bottom=0.15)

    return fig


def calculate_material_stats(segmented, metadata_mask=None):
    """Calculate statistics about material distribution.

    Computes pixel counts and percentages for each material class.

    Args:
        segmented (numpy.ndarray): Segmentation map with material classes.
        metadata_mask (numpy.ndarray, optional): Binary mask defining valid image areas.

    Returns:
        dict: Dictionary with statistics including:
            - pixel_counts: Count of pixels per material
            - percentages: Percentage of each material
            - total_pixels: Total number of valid pixels
    """
    # Updated material labels with LFP and Carbon Black swapped
    material_labels = ["Voids", "LFP", "Carbon Black", "NaCl"]

    # Only count valid pixels (not in metadata area)
    if metadata_mask is not None:
        valid_pixels = segmented[metadata_mask]
        total_pixels = len(valid_pixels)
    else:
        valid_pixels = segmented.flatten()
        total_pixels = segmented.size

    # Count pixels in each class
    class_counts = np.bincount(valid_pixels.flatten(), minlength=4)
    class_percentages = class_counts / total_pixels * 100

    # Create statistics dictionary
    stats = {
        "pixel_counts": {material_labels[i]: int(class_counts[i]) for i in range(4)},
        "percentages": {material_labels[i]: float(class_percentages[i]) for i in range(4)},
        "total_pixels": int(total_pixels)
    }

    # Print results
    print("\nMaterial Distribution Analysis:")
    print("-" * 40)
    for i, material in enumerate(material_labels):
        print(f"{material}: {class_percentages[i]:.2f}% ({class_counts[i]} pixels)")
    print("-" * 40)

    return stats


def export_to_csv(segmented, image_path, output_path, metadata_mask=None):
    """Export segmentation results to CSV.

    Creates a CSV file containing pixel coordinates and
    corresponding material classifications.

    Args:
        segmented (numpy.ndarray): Segmentation map with material classes.
        image_path (str): Path to the original image file.
        output_path (str): Path to save the CSV file.
        metadata_mask (numpy.ndarray, optional): Binary mask defining valid image areas.
    """
    # Updated material labels with LFP and Carbon Black swapped
    material_labels = ["Voids", "LFP", "Carbon Black", "NaCl"]
    h, w = segmented.shape

    # Create coordinate grids
    y_indices, x_indices = np.indices((h, w))

    # If we have a metadata mask, only include valid pixels
    if metadata_mask is not None:
        # Get positions of valid pixels
        valid_y = y_indices[metadata_mask]
        valid_x = x_indices[metadata_mask]
        valid_labels = segmented[metadata_mask]

        # Create corresponding material labels
        material_column = [material_labels[label] for label in valid_labels]

        # Create pixel coordinates
        pixels = [f"({x}, {y})" for x, y in zip(valid_x, valid_y)]

        # Create DataFrame
        df = pd.DataFrame({
            "ImageName": [os.path.basename(image_path)] * len(valid_y),
            "Pixel": pixels,
            "Class": valid_labels,
            "Material": material_column,
            "X": valid_x,
            "Y": valid_y
        })
    else:
        # Include all pixels
        x_flat = x_indices.flatten()
        y_flat = y_indices.flatten()
        labels_flat = segmented.flatten()

        # Create material label column
        material_column = [material_labels[label] for label in labels_flat]

        # Create pixel coordinates
        pixels = [f"({x}, {y})" for x, y in zip(x_flat, y_flat)]

        # Create DataFrame
        df = pd.DataFrame({
            "ImageName": [os.path.basename(image_path)] * len(x_flat),
            "Pixel": pixels,
            "Class": labels_flat,
            "Material": material_column,
            "X": x_flat,
            "Y": y_flat
        })

    # Save to CSV
    df.to_csv(output_path, index=False)


def main():
    """Main function to handle command-line arguments.

    Parses command-line arguments and calls the segmentation function with
    appropriate parameters.

    Returns:
        int: Exit code (0 for success, 1 for errors).
    """
    parser = argparse.ArgumentParser(description='SEM Image Segmentation with GMM, Autoencoder, and SAM Masks')

    parser.add_argument('image_path', help='Path to the SEM image file (.png)')
    parser.add_argument('--masks',
                        help='Path to SAM masks pickle file (.pkl) - if not provided, will use same base name as image')
    parser.add_argument('--output', help='Output directory for results', default='gmm_sam_results')
    parser.add_argument('--void-threshold', type=int, default=10,
                        help='Threshold for void detection (lower = fewer voids)')
    parser.add_argument('--epochs', type=int, default=50, help='Number of epochs for autoencoder training (0 to skip)')
    parser.add_argument('--gmm-components', type=int, default=4, help='Number of GMM components')

    args = parser.parse_args()

    # Validate image path
    if not os.path.isfile(args.image_path):
        print(f"Error: Image file not found: {args.image_path}")
        return 1

    # If masks path not provided, infer it from image path
    masks_path = args.masks
    if masks_path is None:
        base_name = os.path.splitext(args.image_path)[0]
        masks_path = f"{base_name}.pkl"

    if not os.path.isfile(masks_path):
        print(f"Error: Masks file not found: {masks_path}")
        return 1

    # Run the segmentation
    segment_with_gmm_sam(
        args.image_path,
        masks_path=masks_path,
        output_dir=args.output,
        void_threshold=args.void_threshold,
        epochs=args.epochs,
        gmm_components=args.gmm_components
    )

    return 0


if __name__ == "__main__":
    sys.exit(main())